
sudo: false

language: ruby

cache: bundler

services:
  - postgresql
  - mysql

gemfile:
  - gemfiles/active_record_60.gemfile
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_50.gemfile

env:
  - DB=sqlite3
  - DB=postgresql
  - DB=mysql

before_install: gem install bundler
install: bundle install --jobs=3 --retry=3 --no-deployment
script: bundle exec rspec


matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/active_record_60.gemfile
    - rvm: 2.3
      gemfile: gemfiles/active_record_60.gemfile


