sqlite3: &sqlite3
  adapter: sqlite3
  database: db/pagy_test.sqlite3
  pool: 5
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  database: pagy_test

mysql: &mysql
  adapter: mysql2
  host: <%= ENV.fetch("DB_HOST", '127.0.0.1') %>
  username: root
  password: <%= ENV["DB_PASSWORD"] %>
  database: pagy_test

test:
  <<: *<%= ENV['DB'] %>
